spring:
  datasource:
    username: streben
    url: jdbc:postgresql://localhost:5432/db_employee
    password: streben
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: update
server:
  port: 8081
  servlet:
    context-path: /demo-employee
  error:
    include-stacktrace: never

 